<<<<<<< HEAD
include: package:lint/analysis_options.yaml
linter:
  rules:
=======
include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
>>>>>>> 5d47357 (📦 NEW: Add new scaffolding with environments)
