name: flutter_clean_architecture
description: Clean architeture
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  flutter_gen: any
  firebase_core: ^2.27.2
  flutter_riverpod: ^2.5.1
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.2
  hive_flutter: ^1.1.0
dev_dependencies:

  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  mocktail: ^1.0.3


flutter:
  uses-material-design: true
  generate: true
