<<<<<<< HEAD
name: clean_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  lint: ^2.3.0

flutter:

  uses-material-design: true

=======
name: flutter_clean_architecture
description: Clean architeture
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  flutter_gen: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
>>>>>>> 5d47357 (📦 NEW: Add new scaffolding with environments)
